Metrics:
  Enabled: false  # Metrics should never be explicitly used for CI, but can be useful for finding areas to refactor.

Rails:
  Enabled: true  # This is a Rails application, so let's run the Rails cops.

Style/ExtraSpacing:
  Enabled: false  # We like to put extra spaces before one-liner comments.

Style/GuardClause:
  Enabled: false  # Sometimes the guard clause suggestions would make lines too long, since we disable line-length metrics.

Style/IndentationConsistency:
  EnforcedStyle: rails  # We indent private/protected methods as per Rails style.

Style/RaiseArgs:
  EnforcedStyle: compact  # We prefer the compact exception raising style.

Style/StringLiterals:
  Enabled: false  # We don't really care about ''/"" consistency; changing all our strings would be messy.
