# AWS configuration.
development:
  access_key_id: AKIA1111111111111UA
  secret_access_key: secret
  endpoint: http://localhost:8000

test:
  access_key_id: AKIA1111111111111UA
  secret_access_key: secret
  endpoint: http://localhost:8001
