# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b714509650504eaa786e181ad638b81863e3ddd85d338615fc97d5971c1f29b787b860e357add56cd3e9f2270c6af5987b2f5124d3efd3dfc68dd7c52c85958a

test:
  secret_key_base: 3b5db199004c4490259a6d4156c5173402f8ae45f3357ff4f98abb4779f4517e57906c9f30bae8164782dd0456f2a8691c7c3ad7e77c7c93ff66cf74869c0d6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
